---
- hosts: all
  gather_facts: yes
  vars:
    required_packages:
      - "python3-pip"
      - "default-jre"
      - "net-tools"

  tasks:

  - name: Upgrade all packages
    apt:
      name: "*"
      state: latest
      update_cache: yes

  - name: Install required packages
    apt:
      name: "{{ required_packages }}"

  - name: Install cmm tool
    pip:
      name: ccm
      state: latest
    
